name: CI Pipeline

on:
  push:
    branches:
      - dev
      - modeling
  pull_request:
    branches:
      - dev
      - modeling


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 📦 Install hatch
        run: pip install hatch

      - name: 📥 Install project dependencies
        run: hatch env create

      - name: ✅ Run training pipeline
        run: hatch run python -m src.scripts.train
